### ISSUE TITLE
Empty/Nested Except Statements

### ISSUE THREAD

**Issue by aloutfi** [hermda02/joint_fit#1]
https://github.com/hermda02/joint_fit/blob/e5b6fb6a28155c4a1ad20cf0e48998fc9e912ae9/scripts/corner_test.py#L23-L29

https://github.com/hermda02/joint_fit/blob/e5b6fb6a28155c4a1ad20cf0e48998fc9e912ae9/scripts/corner_two.py#L21-L28

Per the Zen of Python: Errors should never pass silently. What error are you getting?
For starters, maybe something like...
```
targets = ['pixel_350_', '.dat']
for target in targets:
    file = file.replace(target,'')
labels.append(file)
```
and then a try except over the part that's causing the issue.

**Comment by hermda02** [comment]
Code deprecated
