### ISSUE TITLE
string interpolation

### ISSUE THREAD

**Issue by aloutfi** [hermda02/joint_fit#3]
https://github.com/hermda02/joint_fit/blob/e5b6fb6a28155c4a1ad20cf0e48998fc9e912ae9/scripts/dust_amp_sed.py#L24

https://github.com/hermda02/joint_fit/blob/e5b6fb6a28155c4a1ad20cf0e48998fc9e912ae9/scripts/dust_amp_sed.py#L19

In 3.6, python introduced[ f-strings](https://www.python.org/dev/peps/pep-0498/#id23). Took me a sec to get used to them but they result in much cleaner code with fewer edge cases to fix.

`print(f"Data files have {np.shape(dust_Q)[0]} iterations.")`

**Comment by hermda02** [comment]
Great advice
